System hostname = openbsd-zart
Password for root = zart123
Allow root ssh login = yes
Setup a user = dev
Password for user dev = zart123
Public ssh key for user dev = none
What timezone are you in = Asia/Tokyo
Which disk is the root disk = sd0
Use (W)hole disk MBR, whole disk (G)PT or (E)dit = whole
Use (A)uto layout, (E)dit auto layout, or create (C)ustom layout = a
Location of sets = http
HTTP Server = cdn.openbsd.org
Set name(s) = +comp79.tgz
Set name(s) = done
